server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shoppingdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:secretpassword}

spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
server.error.include-message=always
