apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine

        ports:
        - containerPort: 5432

        env:
        - name: POSTGRES_DB
          value: shoppingdb

        - name: POSTGRES_USER
          value: admin

        - name: POSTGRES_PASSWORD
          value: secretpassword

        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data

        - name: postgres-init
          mountPath: /docker-entrypoint-initdb.d

      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-data-pvc

      - name: postgres-init
        configMap:
          name: postgres-init

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc

spec:
  type: ClusterIP

  selector:
    app: postgres

  ports:
  - port: 5432
    targetPort: 5432
