CREATE TABLE IF NOT EXISTS shop_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(80) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  description VARCHAR(500) NOT NULL,
  price_cents INTEGER NOT NULL CHECK (price_cents >= 0)
);
CREATE TABLE IF NOT EXISTS cart_items (
  user_id BIGINT NOT NULL REFERENCES shop_users(id),
  product_id BIGINT NOT NULL REFERENCES products(id),
  quantity INTEGER NOT NULL CHECK (quantity BETWEEN 1 AND 99),
  PRIMARY KEY (user_id, product_id)
);
CREATE TABLE IF NOT EXISTS shop_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES shop_users(id),
  recipient VARCHAR(120) NOT NULL,
  address VARCHAR(250) NOT NULL,
  city VARCHAR(120) NOT NULL,
  total_cents BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS order_items (
  order_id BIGINT NOT NULL REFERENCES shop_orders(id),
  product_id BIGINT NOT NULL REFERENCES products(id),
  name VARCHAR(120) NOT NULL,
  unit_price_cents INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  PRIMARY KEY (order_id, product_id)
);
INSERT INTO products (id, name, description, price_cents) VALUES
  (1, 'Laptop', 'Portable computer', 99900),
  (2, 'Keyboard', 'Mechanical keyboard', 9900),
  (3, 'Mouse', 'Wireless mouse', 4900)
ON CONFLICT (id) DO NOTHING;
